# greenhouse_gateway/subscriber.py
#
# WHAT THIS FILE DOES:
#   Shelly sensors send their readings to Mosquitto (the MQTT broker running on greenhouse MacBook).
#   This script connects to Mosquitto, listens for those readings, pulls out the values we
#   care about, and prints each reading.


import json
from datetime import datetime, timezone       
import paho.mqtt.client as mqtt             # type: ignore


def normalize(data):
    # All the sensor values live under "params"
    p = data["params"]
    return {
        "sensor_id": data["src"], #based on device MAC address -> guaranteed to be unique
        "sensor_name": data["dst"].split("/")[0], #this will likely be a zone label at some point
        "ts": datetime.now(timezone.utc).isoformat(), #timestamp generated by script at time of message (not using shelly for this)
        "temp_c": p["temperature:0"]["tC"],
        "humidity": p["humidity:0"]["rh"],
        "battery": p["devicepower:0"]["battery"]["percent"],
    }


# ---------------------------------------------------------------------------------------------
# CALLBACK 1: runs automatically every time we connect (or reconnect) to the broker.
#
# You never call this function yourself. paho calls it for you and always passes these 5 values:
#   client              - the MQTT client object
#   userdata(unused)    - optional custom data you can attach to the client
#   flags(unused)       - extra details about the connection
#   reason_code(unused) - whether the connection succeeded (0 / "Success") or why it failed
#   properties(unused ) - extra MQTT v5 info
#
# paho requires all 5 parameters to be listed, even the ones we ignore.
# ---------------------------------------------------------------------------------------------
def on_connect(client, userdata, flags, reason_code, properties):
    # Tell the broker which messages we want. 
    # "+" is a wildcard that matches any single word -> catches every Shelly device.
    # function runs on every reconnect so our subscription never gets dropped.
    client.subscribe("+/events/rpc")


# ---------------------------------------------------------------------------------------------
# CALLBACK 2: runs automatically every time a message arrives on a topic we subscribed to.
#
#   client   - the MQTT client object
#   userdata (unused) - reaches state without global variable
#   msg      - the message itself. The two parts we care about:
#                msg.topic   -> which topic it came from, e.g. "shellyhtg3-a1b2c3/events/rpc"
#                msg.payload -> the message content, as raw bytes of JSON text
#
# paho requires all 3 parameters to be listed, even the ones we ignore.
# ---------------------------------------------------------------------------------------------
def on_message(client, userdata, msg):
    try:
        # Convert the raw JSON bytes into a Python dictionary we can read with data["key"].
        data = json.loads(msg.payload)
        
        # Shelly sends several kinds of messages. "method" says which kind this one is.
        # "NotifyFullStatus" is the complete report the sensor sends each time it wakes up,
        # return here means that the method is not NotifyFullStatus so we will ignore those messages
        if data.get("method") != "NotifyFullStatus":
            return        
        
        # Build reading into a data shape in normalize() function
        # reading variable below will eventually be sent to api
        reading = normalize(data)
        print(reading)

    # Exception catches any error and then prints out error message
    except Exception as e:
        print("skipped:", e)


if __name__ == "__main__":

    # Create the MQTT client.
    # It must be unique: if two clients use the same ID, the broker kicks older one off.
    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id="greenhouse-gateway")

    # Tell the client which of our functions to call for each event
    client.on_connect = on_connect
    client.on_message = on_message

    # Connect to the broker.
    #   "localhost" - the broker is on this same machine (Mosquitto on the MacBook)
    #   1883        - the standard MQTT port (Mosquitto's default)
    #   1884        - because currently ssh tunneling into greenhouse macbook from personal mac
    #               - this will be changed back to port 1883 when running inside greenhouse
    client.connect("localhost", 1884)

    # Run forever: wait for messages, call on_message for each one, and reconnect automatically
    # if the connection drops the script stays on this line until you press Ctrl+C.
    try:
        client.loop_forever()
    except KeyboardInterrupt:
        #exit gracefully
        client.disconnect()